client:
  config:
    publicRuntimeConfig:
      apiServer: https://api-dev.rdlxr.com
      appServer: https://dev.rdlxr.com
      gameserver: https://gameserver-dev.rdlxr.com
      gameserverDomain: gameserver-dev.rdlxr.com
      dev: true
      gaMeasurementId: '<GOOGLE_ANALYTICS_MEASUREMENT_ID>'
      feathersStoreKey: TheOverlay-Auth-Store
      localStorageKey: theoverlay-client-store-key-v1
      loginDisabled: true
      logo: "./logo.svg"
      rootRedirect: false
      siteDescription: Connected Worlds for Everyone
      siteTitle: XREngine
      title: "The Overlay"
      auth:
        enableSmsMagicLink: true
        enableEmailMagicLink: true
        enableUserPassword: true
        enableGithubSocial: true
        enableFacebookSocial: true
        enableGoogleSocial: true
        enableLinkedInSocial: true
        enableTwitterSocial: true
      alert:
        timeout: 10000
      offlineMode: false
      staticPages:
        termsOfService: "/terms-of-service"
  extraEnv:
    API_ASSETS_ROUTE: /static-resource
    API_ASSETS_ACTION: assets
    API_MEDIA_ROUTE: /media
    API_MEDIA_SEARCH_ROUTE: "-search"
    API_META_ROUTE: /meta
    API_PROJECTS_ROUTE: /project
    API_RESOLVE_MEDIA_ROUTE: /resolve-media
    API_PROJECT_PUBLISH_ACTION: /publish-project
    API_SCENES_ROUTE: /collection
    API_SERVER_ADDRESS: api-dev.rdlxr.com
    API_SOCKET_ENDPOINT: /socket
    API_SERVER: https://api-dev.rdlxr.com
    APP_ENV: production
    CLIENT_ADDRESS: https://dev.rdlxr.com
    CLIENT_ENABLED: "true"
    CLIENT_SCENE_ROUTE: /scenes/
    CLIENT_LOCAL_SCENE_ROUTE: "/scene.html?scene_id="
    CORS_PROXY_SERVER: https://api-dev.rdlxr.com
    HOST_IP: https://api-dev.rdlxr.com
    HOST_PORT: "3000"
    GITHUB_ORG: xrengine
    GITHUB_REPO: spoke
    IS_MOZ: "false"
    NEXT_PUBLIC_API_SERVER: https://api-dev.rdlxr.com
    NODE_ENV: production
    NON_CORS_PROXY_DOMAINS: "reticulum.io,rdlxr.com,amazonaws.com"
    ROUTER_BASE_PATH: /spoke
    SERVER_ENABLED: "false"
    SITE_DESC: Connected Worlds for Everyone
    SITE_TITLE: TheOverlay
    THUMBNAIL_ROUTE: /thumbnail/
    THUMBNAIL_SERVER: https://api-dev.rdlxr.com
    USE_DIRECT_UPLOAD_API: "true"
    USE_HTTPS: "true"
  image:
    repository: 283786857250.dkr.ecr.eu-west-2.amazonaws.com/xrengine-dev-builder
    pullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - XREngineNodeGroup
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: dev.rdlxr.com
        paths:
          - /
  replicaCount: 1
  service:
    type: NodePort
domain: rdlxr.com
mariadb:
  db:
    name: xrengine
    password: password
    user: admin
  enabled: false
  externalHost: xrengine-instance-1.ch9hdiax2wxa.eu-west-2.rds.amazonaws.com
rts:
  extraEnv:
    NAF_LISTEN_PORT: "8081"
api:
  config:
    aws:
      keys:
        access_key_id: <AWS_ACCESS_KEY>
        secret_access_key: <AWS_SECRET_KEY>
      s3:
        region: eu-west-2
        static_resource_bucket: xrengine-static-resources-dev
      cloudfront:
        domain: resources.rdlxr.com
      sns:
        access_key_id: <AWS_ACCESS_KEY>
        application_id: <AWS_SNS_APPLICATION_ID>
        region: eu-west-2
        secret_access_key: <AWS_ACCESS_KEY>
        sender_id: <AWS_SNS_SENDER_ID>
    host: https://dev.rdlxr.com/
  extraEnv:
    APP_ENV: production
    APP_HOST: dev.rdlxr.com
    APP_URL: https://dev.rdlxr.com
    AUTH_SECRET: <INSERT_A_UUID_OR_SOMETHING_SIMILAR>
    AWS_SMS_ACCESS_KEY_ID: <AWS_ACCESS_KEY>
    AWS_SMS_REGION: eu-west-2
    AWS_SMS_SECRET_ACCESS_KEY: <AWS_ACCESS_KEY>
    AWS_SMS_TOPIC_ARN: arn:aws:sns:eu-west-2:283786857250:xrengine
    CLIENT_ENABLED: "false"
    CERT: certs/cert.pem
    KEY: certs/key.pem
    FACEBOOK_CALLBACK_URL: https://dev.rdlxr.com/auth/oauth/facebook
    FACEBOOK_CLIENT_ID: "<FB_OAUTH_CLIENT_ID>"
    FACEBOOK_CLIENT_SECRET: "<FB_OAUTH_SECRET>"
    FORCE_DB_REFRESH: "false"
    GAMESERVER_DOMAIN: gameserver-dev.rdlxr.com
    GITHUB_CALLBACK_URL: https://dev.rdlxr.com/auth/oauth/github
    GITHUB_CLIENT_ID: "<GITHUB_OAUTH_CLIENT_ID>"
    GITHUB_CLIENT_SECRET: "<GITHUB_OAUTH_SECRET>"
    GOOGLE_CALLBACK_URL: https://dev.rdlxr.com/auth/oauth/google
    GOOGLE_CLIENT_ID: "<GOOGLE_OAUTH_CLIENT_ID>"
    GOOGLE_CLIENT_SECRET: "<GOOGLE_OAUTH_SECRET>"
    LINKEDIN_CALLBACK_URL: https://dev.theoverlay.io/auth/oauth/linkedin
    LINKEDIN_CLIENT_ID: "<LINKEDIN_OAUTH_CLIENT_ID"
    LINKEDIN_CIENT_SECRET: "<LINKEDIN_OAUTH_CLIENT_SECRET>"
    MAGICLINK_EMAIL_SUBJECT: Login to TheOverlay
    MAIL_FROM: info@login.rdlxr.com
    SERVER_ENABLED: "true"
    SERVER_HOST: "api-dev.rdlxr.com"
    SERVER_PORT: "3030"
    SMTP_FROM_EMAIL: info@login.rdlxr.com
    SMTP_FROM_NAME: noreply
    SMTP_HOST: email-smtp.eu-west-2.amazonaws.com
    SMTP_PASS: BEY2HmewCFXOD7EF0cjFzvBixPWnyWE43doA6YZOwJji
    SMTP_PORT: "465"
    SMTP_SECURE: "true"
    SMTP_USER: AKIAUEEYDZMRFNC4FYTC
    STORAGE_PROVIDER: aws
    STORAGE_AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY>
    STORAGE_AWS_ACCESS_KEY_SECRET: <AWS_SECRET_KEY>
    STORAGE_CLOUDFRONT_DOMAIN: resources.rdlxr.com
    STORAGE_CLOUDFRONT_DISTRIBUTION_ID: E3OX25EL0GBWWY
    STORAGE_S3_REGION: eu-west-2
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources-dev
    STORAGE_S3_AVATAR_DIRECTORY: avatars
    TWITTER_CALLBACK_URL: https://dev.theoverlay.io/auth/oauth/linkedin
    TWITTER_CLIENT_ID: "<TWITTER_OAUTH_CLIENT_ID>"
    TWITTER_CIENT_SECRET: "<TWITTER_OAUTH_CLIENT_ID>"
    DEFAULT_AVATAR_ID: Allison
    AVATAR_FILE_ALLOWED_EXTENSIONS: ".glb,.gltf,.vrm,.fbx"
    MIN_AVATAR_FILE_SIZE: "0"
    MAX_AVATAR_FILE_SIZE: "15728640"
    MIN_THUMBNAIL_FILE_SIZE: "0"
    MAX_THUMBNAIL_FILE_SIZE: "2097152"
    STORAGE_S3_DEV_MODE: dev
    PRESIGNED_URL_EXPIRATION_DURATION: "3600"
  image:
    repository: 283786857250.dkr.ecr.eu-west-2.amazonaws.com/xrengine-dev-builder
  service:
    type: NodePort
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - XREngineNodeGroup
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/server-snippet: |
        location ~* /cors-proxy/(.*) {
          proxy_http_version 1.1;
          proxy_pass_request_headers on;
          proxy_hide_header Access-Control-Allow-Origin;
          add_header Access-Control-Allow-Origin $http_origin;
          proxy_intercept_errors on;
          error_page 301 302 307 = @handle_redirects;
          proxy_pass https://$1?$args;
        }

        location @handle_redirects {
          set $saved_redirect_location '$upstream_http_location';
          proxy_pass_request_headers on;
          proxy_hide_header Access-Control-Allow-Origin;
          add_header Access-Control-Allow-Origin "$http_origin";
          proxy_pass $saved_redirect_location;
        }
    hosts:
      - host: api-dev.rdlxr.com
        paths:
          - /
  replicaCount: 2

release:
  name: dev

media:
  enabled: false
  config:
    aws:
      keys:
        access_key_id: <AWS_ACCESS_KEY>
        secret_access_key: <AWS_SECRET_KEY>
      s3:
        region: eu-west-2
        static_resource_bucket: xrengine-static-resources-dev
      cloudfront:
        domain: resources.rdlxr.com
      sns:
        access_key_id: <AWS_ACCESS_KEY>
        application_id: <AWS_SNS_APPLICATION_ID>
        region: eu-west-2
        secret_access_key: <AWS_ACCESS_KEY>
        sender_id: <AWS_SNS_SENDER_ID>
    host: https://dev.rdlxr.com/
  extraEnv:
    APP_ENV: production
    APP_HOST: dev.rdlxr.com
    APP_URL: https://dev.rdlxr.com
    AUTH_SECRET: <INSERT_A_UUID_OR_SOMETHING_SIMILAR>
    AWS_SMS_ACCESS_KEY_ID: <AWS_ACCESS_KEY>
    AWS_SMS_REGION: eu-west-2
    AWS_SMS_SECRET_ACCESS_KEY: <AWS_SECRET_KEY>
    AWS_SMS_TOPIC_ARN: arn:aws:sns:eu-west-2:283786857250:xrengine
    FACEBOOK_CALLBACK_URL: https://dev.rdlxr.com/auth/oauth/facebook
    FACEBOOK_CLIENT_ID: "<FB_OAUTH_CLIENT_ID>"
    FACEBOOK_CLIENT_SECRET: "<FB_OAUTH_SECRET>"
    FORCE_DB_REFRESH: "false"
    GITHUB_CALLBACK_URL: https://dev.rdlxr.com/auth/oauth/github
    GITHUB_CLIENT_ID: "<GITHUB_OAUTH_CLIENT_ID>"
    GITHUB_CLIENT_SECRET: "<GITHUB_OAUTH_SECRET>"
    GOOGLE_CALLBACK_URL: https://dev.rdlxr.com/auth/oauth/google
    GOOGLE_CLIENT_ID: "<GOOGLE_OAUTH_CLIENT_ID>"
    GOOGLE_CLIENT_SECRET: "<GOOGLE_OAUTH_SECRET>"
    MAGICLINK_EMAIL_SUBJECT: Login to TheOverlay
    MAIL_FROM: info@login.rdlxr.com
    SERVER_ENABLED: "true"
    SERVER_HOST: "api-dev.rdlxr.com"
    SMTP_FROM_EMAIL: info@login.rdlxr.com
    SMTP_FROM_NAME: noreply
    SMTP_HOST: email-smtp.eu-west-2.amazonaws.com
    SMTP_PASS: BEY2HmewCFXOD7EF0cjFzvBixPWnyWE43doA6YZOwJji
    SMTP_PORT: "465"
    SMTP_SECURE: "true"
    SMTP_USER: AKIAUEEYDZMRFNC4FYTC
    STORAGE_PROVIDER: aws
    STORAGE_AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY>
    STORAGE_AWS_ACCESS_KEY_SECRET: <AWS_SECRET_KEY>
    STORAGE_CLOUDFRONT_DOMAIN: resources.rdlxr.com
    STORAGE_CLOUDFRONT_DISTRIBUTION_ID: E3OX25EL0GBWWY
    STORAGE_S3_REGION: eu-west-2
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources-dev
  image:
    repository: 283786857250.dkr.ecr.eu-west-2.amazonaws.com/xrengine-dev-builder
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - XREngineNodeGroup
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: https://dev.rdlxr.com
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
    hosts:
      - host: api-dev.rdlxr.com
        paths:
          - /video
  service:
    type: NodePort

gameserver:
  image:
    repository: 283786857250.dkr.ecr.eu-west-2.amazonaws.com/xrengine-dev-builder
    pullPolicy: IfNotPresent
  extraEnv:
    APP_ENV: production
    APP_HOST: dev.rdlxr.com
    AUTH_SECRET: <SAME_AUTH_SECRET_AS_IN_API>
    APP_URL: https://dev.rdlxr.com
    GAMESERVER_ENABLED: "true"
    ROUTE53_ACCESS_KEY_ID: <AWS_ACCESS_KEY>
    ROUTE53_ACCESS_KEY_SECRET: <AWS_SECRET_KEY>
    ROUTE53_HOSTED_ZONE_ID: Z078118524NWPVD45FKBB
    RTC_START_PORT: "40000"
    RTC_END_PORT: "40099"
    RTC_PORT_BLOCK_SIZE: "100"
    GAMESERVER_DOMAIN: gameserver-dev.rdlxr.com
    GAMESERVER_PORT: "3031"
    STORAGE_PROVIDER: aws
    STORAGE_AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY>
    STORAGE_AWS_ACCESS_KEY_SECRET: <AWS_SECRET_KEY>
    STORAGE_CLOUDFRONT_DOMAIN: resources.rdlxr.com
    STORAGE_CLOUDFRONT_DISTRIBUTION_ID: E3OX25EL0GBWWY
    STORAGE_S3_REGION: eu-west-2
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources-dev
    CERT: certs/cert.pem
    KEY: certs/key.pem
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/server-snippet: |
        location ~* /socket.io/([a-zA-Z0-9\.]*)/([a-zA-Z0-9\.]*)/?$ {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://$1:$2/socket.io/?$args;
        }
    host: gameserver-dev.rdlxr.com
  resources:
    limits:
      cpu: "2"
    requests:
      cpu: "1.5"
  buffer:
    bufferSize: 2
    minReplicas: 4
    maxReplicas: 24
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - ng-gameservers-1

editor:
  enabled: false
  extraEnv:
    BASE_ASSETS_PATH: https://api-dev.rdlxr.com/
    CORS_PROXY_SERVER: ""
    GA_TRACKING_ID: ""
    HUBS_SERVER: api-dev.rdlxr.com
    IS_MOZ: "false"
    NON_CORS_PROXY_DOMAINS: ""
    RETICULUM_SERVER: api-dev.rdlxr.com
    SENTRY_DSN: ""
    THUMBNAIL_SERVER: ""
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - XREngineNodeGroup
  ingress:
    hosts:
      - host: dev.rdlxr.com
        paths:
          - /create
redis:
  enabled: false

analytics:
  enabled: false
  name: xrengine-analytics
  replicaCount: 1
  image:
    repository: 283786857250.dkr.ecr.eu-west-2.amazonaws.com/xrengine-dev-builder
    pullPolicy: IfNotPresent
  extraEnv:
    ANALYTICS_ENABLED: "true"
    ANALYTICS_PORT: "3030"
    ANALYTICS_PROCESS_INTERVAL: "10000"
    AUTH_SECRET: <SAME_AUTH_SECRET_AS_IN_API>
    STORAGE_S3_REGION: eu-west-2
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources-dev
    STORAGE_S3_AVATAR_DIRECTORY: avatars


  service:
    type: ClusterIP
    port: 3030

  serviceAccount:
    create: true
    annotations: {}
    name:

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - XREngineNodeGroup
