mariadb:
  db:
    name: xrengine
    password: password
    user: admin
  enabled: false
  externalHost: xrengine-instance-1.ch9hdiax2wxa.eu-west-2.rds.amazonaws.com
builder:
  extraEnv:
    RELEASE_NAME: dev
    AWS_ACCESS_KEY: <AWS_ACCESS_KEY>
    AWS_SECRET: <AWS_SECRET_KEY>
    AWS_REGION: eu-west-2
    CLUSTER_NAME: XREngine
    ECR_URL: 283786857250.dkr.ecr.eu-west-2.amazonaws.com
    REPO_NAME: xrengine-dev
    DOCKER_LABEL: lagunalabs/xrengine
    PRIVATE_ECR: "true"
    STORAGE_PROVIDER: aws
    STORAGE_AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY>
    STORAGE_AWS_ACCESS_KEY_SECRET: <AWS_SECRET_KEY>
    STORAGE_CLOUDFRONT_DOMAIN: https://d29z74qdbqejgb.cloudfront.net
    STORAGE_CLOUDFRONT_DISTRIBUTION_ID: E3OX25EL0GBWWY
    STORAGE_S3_REGION: eu-west-2
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources-dev
    STORAGE_S3_AVATAR_DIRECTORY: avatars
  image:
    repository: 283786857250.dkr.ecr.eu-west-2.amazonaws.com/xrengine-dev-builder
  service:
    type: NodePort
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - ng-dev-builder-1
  replicaCount: 1

release:
  name: dev
